config-sparse:
  modules:
    ucp2-legacy:
      config:
        ai_resources_rebuy:
          flour:
            contents:
              suggested-value:
                enabled: true
                sliderValue: 7
          iron:
            contents:
              suggested-value:
                enabled: true
                sliderValue: 7
          wood:
            contents:
              suggested-value:
                enabled: true
                sliderValue: 7
        ai_demolish:
          ai_demolish_eco:
            enabled:
              contents:
                suggested-value: false
          ai_demolish_walls:
            enabled:
              contents:
                suggested-value: true
          ai_demolish_trapped:
            enabled:
              contents:
                suggested-value: true
        ai_attacklimit:
          contents:
            suggested-value:
              enabled: true
              sliderValue: 3000
        ai_addattack:
          contents:
            suggested-value:
              enabled: true
              choice: relative
              choices:
                absolute:
                  slider: 50
                relative:
                  slider: 0.5
        o_freetrader:
          enabled:
            contents:
              suggested-value: false
        fix_apple_orchard_build_size:
          enabled:
            contents:
              suggested-value: true
        o_healer:
          enabled:
            contents:
              suggested-value: true
        o_responsivegates:
          enabled:
            contents:
              suggested-value: true
        u_spearmen_run:
          enabled:
            contents:
              suggested-value: true
        o_restore_arabian_engineer_speech:
          enabled:
            contents:
              suggested-value: false
        o_fast_placing:
          enabled:
            contents:
              suggested-value: false
        o_engineertent:
          enabled:
            contents:
              suggested-value: true
        o_gamespeed:
          enabled:
            contents:
              suggested-value: true
        o_moatvisibility:
          enabled:
            contents:
              suggested-value: true
        o_default_multiplayer_speed:
          contents:
            suggested-value:
              enabled: false
              sliderValue: 60
        o_firecooldown:
          contents:
            suggested-value:
              enabled: false
              sliderValue: 2500
        ai_recruitstate_initialtimer:
          contents:
            suggested-value:
              enabled: true
              sliderValue: 0
    aicloader:
      config:
        failureHandling:
          contents:
            suggested-value: FATAL_LOG
    aiSwapper:
      config: {}
  plugins:
    ucp2-legacy-defaults:
      config: {}
meta:
  version: 1.0.0
